api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('', views.index, name='index'),
    path('countlines/', views.countlines, name='countlines'),
    path('getcwd/', views.getcwd, name='getcwd'),
    path('generateNewPredictions/', views.generate_new_predictions,
         name='generateNewPredictions'),
    path('generatePredictionsString/', views.generate_predictions_string,
         name='generatePredictionsString'),
    path('fastText/', views.fasttext, name='fasttext'),
]

api/models.py
from django.db import models

# Create your models here.

api/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from .bashScripts import pwd, countLines, FT_predict, FT_train_predict, FT_predict_string


def index(request):
    return render(request, 'api/index.html')


def countlines(request):
    numlines = countLines()
    return render(request, 'api/bashResult.html', {'result': numlines})


def getcwd(request):
    cwd = pwd()
    return render(request, 'api/bashResult.html', {'result': cwd})

# Generate predictions with new data and pre-trained cooking model


def generate_new_predictions(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        fs.save(myfile.name, myfile)
        predictions = FT_predict(myfile.name)
        return render(request, 'api/BashResult.html', {'result': predictions})
    return render(request, 'api/generatePredictions.html')

# Generate predictions from text input


def generate_predictions_string(request):
    if request.method == 'POST':
        string = request.POST['string']
        predictions = FT_predict_string(string)
        return render(request, 'api/generatePredictionsString.html', {'result': predictions})
    return render(request, 'api/generatePredictionsString.html')

# Train new fastText classification model and generate predictions


def fasttext(request):
    modelData = 'cooking.txt'
    validationData = 'cooking.val'
    if request.method == 'POST':
        modelDataFile = request.FILES['modelDataFile']
        validationDataFile = request.FILES['validationDataFile']
        fs = FileSystemStorage()
        fs.save(modelDataFile.name, modelDataFile)
        fs.save(validationDataFile.name, validationDataFile)
        modelData = modelDataFile.name
        validationData = validationDataFile.name
        predictions = FT_train_predict(modelData, validationData)
        return render(request, 'api/bashResult.html', {'result': predictions})
    return render(request, 'api/fastText.html')

api/templates/api/bashResult.html
<!DOCTYPE HTML>
<html>

<head>
  <title>Unix2Python</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
    crossorigin="anonymous">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
    crossorigin="anonymous">
  <link rel="stylesheet" href="../../static/css/style2.css">
</head>

<body>
  <section>
    <div class="container">
      {% if result %}
      <p>{{ result }}</p>
      {% else %}
      <h3>A result wasn't able to be obtained. Please try another method.</h3>
      {% endif %}
    </div>
  </section>

  <section>
    <div class="container">
      <p>
        <a href="{% url 'api:index' %}">Return to home</a>
      </p>
    </div>
  </section>

</body>

</html>

api/templates/api/fastText.html
<!DOCTYPE HTML>
<html>

<head>
  <title>Unix2Python</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
    crossorigin="anonymous">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
    crossorigin="anonymous">
  <link rel="stylesheet" href="../../static/css/style2.css">
</head>

<body>
  <section>
    <div class="container">
      <div class="p5">
        <h1>Fast Text</h1>
      </div>
    </div>
  </section>

  <section>
    <div class="container">
      <div class="p5">
        <form method="post" enctype="multipart/form-data">
          <div class="p5">
            <h4>Model</h4>
            <p>This will train a supervised learning model to assign labels to sentences.</p>
            <p>Please select labeled data (.txt) to train a new model.</p>
            {% csrf_token %} Training Data:
            <input type="file" name="modelDataFile">
          </div>
          <br>
          <div class="p5">
            <h4>Predictions</h4>
            <p>Please select an unlabeled set of sentences (.txt) to generate predicted labels.</p>
            Prediction Data:
            <input type="file" name="validationDataFile">
          </div>
          <br>
          <div class="p5">
            <h4>Submit</h4>
            <p>Train a new model, then generate predictions.</p>
            <p>Warning: This can take a minute.</p>
            <button type="submit">Submit</button>
          </div>
          <br>
        </form>
      </div>
    </div>
  </section>
  <section>
    <div class="container">
      <div class="p-5">
        <p>
          <a href="{% url 'api:index' %}">Return to home</a>
        </p>
      </div>
    </div>
  </section>


</body>

</html>

api/templates/api/generatePredictions.html
<!DOCTYPE HTML>
<html>

<head>
  <title>Unix2Python</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
    crossorigin="anonymous">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
    crossorigin="anonymous">
  <link rel="stylesheet" href="../../static/css/style2.css">
</head>

<body>
  <section>
    <div class="container">
      <div class="p-5">
        <h3>A FastText classification model has been pre-trained using cooking data.</h3>
        <h3>Please select an unlabeled set of sentences (.txt) to generate predicted labels.</h3>
      </div>
    </div>
  </section>
  <section>
    <div class="container">
      <div class="p-5">
        {% load static %} {% block content %}
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="p-5">
            <input type="file" name="myfile">
          </div>
          <br>
          <div class="p-5">
            <button type="submit">Generate Predictions</button>
          </div>
        </form>
      </div>
    </div>
  </section>
  <section>
    <div class="container">
      <div class="p-5">
        <p>
          <a href="{% url 'api:index' %}">Return to home</a>
        </p>
        {% endblock %}
      </div>
    </div>
  </section>
</body>

</html>

api/templates/api/generatePredictionsString.html
<!DOCTYPE HTML>
<html>

<head>
  <title>Unix2Python</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
    crossorigin="anonymous">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
    crossorigin="anonymous">
  <link rel="stylesheet" href="../../static/css/style2.css">
</head>

<body>
  <section>
    <div class="container">
      <div class="p-5">
        <h3>A FastText classification model has been pre-trained using cooking data.</h3>
        <h3>Ask the model some questions to generate predicted labels.</h3>
      </div>
    </div>
  </section>
  <section>
    <div class="container">
      <div class="p-5">
        {% load static %} {% block content %}
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <textarea class="form-control" rows="5" id="comment" name="string"></textarea>
          <br>
          <br>
          <button type="submit">Submit</button>
        </form>
      </div>
    </div>
  </section>
  {% if result %}
  <section>
    <div class="container">
      <div class="p-5">
        <p>{{result}}</p>
      </div>
    </div>
  </section>
  {% endif %}
  <section>
    <div class="container">
      <div class="p-3">
        <p>
          <a href="{% url 'api:index' %}">Return to home</a>
        </p>
        {% endblock %}
      </div>
    </div>
  </section>
</body>

</html>

api/templates/api/index.html
<!DOCTYPE HTML>
<html>

<head>
  <title>Unix2Python</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
    crossorigin="anonymous">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
    crossorigin="anonymous">
  <link rel="stylesheet" href="../../static/css/style2.css">
</head>

<body>
  <section>
    <div class="container">
      <h2>Welcome to the Unix to Python portal.</h2>
      <h4>Choose from a number of options below to run the Unix commands and get the output in your browser.</h4>
    </div>
  </section>

  <section>
    <div class="container">
      <div class="col">
        <div class="p-3">
          <ul>
            <li>
              <a href="{% url 'api:getcwd' %}">Get current working directory</a>
            </li>
            <li>
              <a href="{% url 'api:countlines' %}">Get number of files in current working directory</a>
            </li>
            <li>
              <a href="{% url 'api:generateNewPredictions' %}">Generate new predictions for a pre-trained fastText classification model from a .txt file
              </a>
            </li>
            <li>
              <a href="{% url 'api:generatePredictionsString' %}">Generate new predictions for a pre-trained fastText classification model by typing
              </a>
            </li>
            <li>
              <a href="{% url 'api:fasttext' %}">Train a fastText classification model and generate predictions for the validation set
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>

  <section>

    <img src="https://images.unsplash.com/photo-1531165228670-65ddf39f356a?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=4cc7de315a92b4b399c23288846adbcc&auto=format&fit=crop&w=1950&q=80"
      width="1600" height="1200">

  </section>

</body>

</html>